-- CreateTable
CREATE TABLE "Like" (
"id" SERIAL,
    "authorId" INTEGER NOT NULL,
    "bubbleId" INTEGER NOT NULL,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Like" ADD FOREIGN KEY("authorId")REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Like" ADD FOREIGN KEY("bubbleId")REFERENCES "Bubble"("id") ON DELETE CASCADE ON UPDATE CASCADE;
